# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\FDU\workspace\GUI\Y86\y86.ui'
#
# Created: Wed Jun 12 12:00:46 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Y86Simulator(object):
    def setupUi(self, Y86Simulator):
        Y86Simulator.setObjectName(_fromUtf8("Y86Simulator"))
        Y86Simulator.resize(918, 639)
        Y86Simulator.setStyleSheet(_fromUtf8("QDialog\n"
"{\n"
"background:white;\n"
"}\n"
"QTextBrowser\n"
"{\n"
"border:white;\n"
"}"))
        self.label = QtGui.QLabel(Y86Simulator)
        self.label.setGeometry(QtCore.QRect(30, 20, 201, 31))
        self.label.setStyleSheet(_fromUtf8("font-family:Times;\n"
"font: italic 14pt \"Harrington\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.layoutWidget_2 = QtGui.QWidget(Y86Simulator)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 530, 482, 25))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.runButton = QtGui.QPushButton(self.layoutWidget_2)
        self.runButton.setEnabled(True)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.horizontalLayout.addWidget(self.runButton)
        self.pauseButton = QtGui.QPushButton(self.layoutWidget_2)
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.horizontalLayout.addWidget(self.pauseButton)
        self.stepButton = QtGui.QPushButton(self.layoutWidget_2)
        self.stepButton.setObjectName(_fromUtf8("stepButton"))
        self.horizontalLayout.addWidget(self.stepButton)
        self.backButton = QtGui.QPushButton(self.layoutWidget_2)
        self.backButton.setObjectName(_fromUtf8("backButton"))
        self.horizontalLayout.addWidget(self.backButton)
        self.resetButton = QtGui.QPushButton(self.layoutWidget_2)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.horizontalLayout.addWidget(self.resetButton)
        self.loadAdd = QtGui.QLineEdit(Y86Simulator)
        self.loadAdd.setGeometry(QtCore.QRect(530, 20, 371, 21))
        self.loadAdd.setObjectName(_fromUtf8("loadAdd"))
        self.Slider = QtGui.QSlider(Y86Simulator)
        self.Slider.setGeometry(QtCore.QRect(130, 70, 160, 22))
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName(_fromUtf8("Slider"))
        self.layoutWidget_3 = QtGui.QWidget(Y86Simulator)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 290, 685, 81))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_32 = QtGui.QLabel(self.layoutWidget_3)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_5.addWidget(self.label_32, 0, 9, 1, 1)
        self.textBrowser_47 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_47.sizePolicy().hasHeightForWidth())
        self.textBrowser_47.setSizePolicy(sizePolicy)
        self.textBrowser_47.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_47.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_47.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_47.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_47.setObjectName(_fromUtf8("textBrowser_47"))
        self.gridLayout_5.addWidget(self.textBrowser_47, 2, 9, 1, 1)
        spacerItem = QtGui.QSpacerItem(68, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 6, 1, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget_3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 0, 4, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_5.addWidget(self.label_30, 0, 3, 1, 1)
        self.E_icode = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.E_icode.sizePolicy().hasHeightForWidth())
        self.E_icode.setSizePolicy(sizePolicy)
        self.E_icode.setMinimumSize(QtCore.QSize(0, 20))
        self.E_icode.setMaximumSize(QtCore.QSize(20, 24))
        self.E_icode.setBaseSize(QtCore.QSize(70, 20))
        self.E_icode.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.E_icode.setObjectName(_fromUtf8("E_icode"))
        self.gridLayout_5.addWidget(self.E_icode, 1, 1, 1, 1)
        self.E_valC = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.E_valC.sizePolicy().hasHeightForWidth())
        self.E_valC.setSizePolicy(sizePolicy)
        self.E_valC.setMinimumSize(QtCore.QSize(70, 20))
        self.E_valC.setMaximumSize(QtCore.QSize(70, 24))
        self.E_valC.setBaseSize(QtCore.QSize(70, 20))
        self.E_valC.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.E_valC.setObjectName(_fromUtf8("E_valC"))
        self.gridLayout_5.addWidget(self.E_valC, 1, 3, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 0, 8, 1, 1)
        self.textBrowser_37 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_37.sizePolicy().hasHeightForWidth())
        self.textBrowser_37.setSizePolicy(sizePolicy)
        self.textBrowser_37.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_37.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_37.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_37.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_37.setObjectName(_fromUtf8("textBrowser_37"))
        self.gridLayout_5.addWidget(self.textBrowser_37, 2, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget_3)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_5.addWidget(self.label_27, 0, 5, 1, 1)
        self.E_dstE = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.E_dstE.sizePolicy().hasHeightForWidth())
        self.E_dstE.setSizePolicy(sizePolicy)
        self.E_dstE.setMinimumSize(QtCore.QSize(0, 20))
        self.E_dstE.setMaximumSize(QtCore.QSize(20, 24))
        self.E_dstE.setBaseSize(QtCore.QSize(70, 20))
        self.E_dstE.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.E_dstE.setObjectName(_fromUtf8("E_dstE"))
        self.gridLayout_5.addWidget(self.E_dstE, 1, 7, 1, 1)
        self.textBrowser_39 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_39.sizePolicy().hasHeightForWidth())
        self.textBrowser_39.setSizePolicy(sizePolicy)
        self.textBrowser_39.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_39.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_39.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_39.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_39.setObjectName(_fromUtf8("textBrowser_39"))
        self.gridLayout_5.addWidget(self.textBrowser_39, 2, 7, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_5.addWidget(self.label_28, 0, 7, 1, 1)
        self.textBrowser_40 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_40.sizePolicy().hasHeightForWidth())
        self.textBrowser_40.setSizePolicy(sizePolicy)
        self.textBrowser_40.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_40.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_40.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_40.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_40.setObjectName(_fromUtf8("textBrowser_40"))
        self.gridLayout_5.addWidget(self.textBrowser_40, 2, 8, 1, 1)
        self.E_ifun = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.E_ifun.sizePolicy().hasHeightForWidth())
        self.E_ifun.setSizePolicy(sizePolicy)
        self.E_ifun.setMinimumSize(QtCore.QSize(0, 20))
        self.E_ifun.setMaximumSize(QtCore.QSize(20, 24))
        self.E_ifun.setBaseSize(QtCore.QSize(70, 20))
        self.E_ifun.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.E_ifun.setObjectName(_fromUtf8("E_ifun"))
        self.gridLayout_5.addWidget(self.E_ifun, 1, 2, 1, 1)
        self.E_dstM = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.E_dstM.sizePolicy().hasHeightForWidth())
        self.E_dstM.setSizePolicy(sizePolicy)
        self.E_dstM.setMinimumSize(QtCore.QSize(0, 20))
        self.E_dstM.setMaximumSize(QtCore.QSize(20, 24))
        self.E_dstM.setBaseSize(QtCore.QSize(70, 20))
        self.E_dstM.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.E_dstM.setObjectName(_fromUtf8("E_dstM"))
        self.gridLayout_5.addWidget(self.E_dstM, 1, 8, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 0, 1, 1, 1)
        self.E_valB = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.E_valB.sizePolicy().hasHeightForWidth())
        self.E_valB.setSizePolicy(sizePolicy)
        self.E_valB.setMinimumSize(QtCore.QSize(70, 20))
        self.E_valB.setMaximumSize(QtCore.QSize(70, 24))
        self.E_valB.setBaseSize(QtCore.QSize(70, 20))
        self.E_valB.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.E_valB.setObjectName(_fromUtf8("E_valB"))
        self.gridLayout_5.addWidget(self.E_valB, 1, 5, 1, 1)
        self.E_valA = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.E_valA.sizePolicy().hasHeightForWidth())
        self.E_valA.setSizePolicy(sizePolicy)
        self.E_valA.setMinimumSize(QtCore.QSize(70, 20))
        self.E_valA.setMaximumSize(QtCore.QSize(70, 24))
        self.E_valA.setBaseSize(QtCore.QSize(70, 20))
        self.E_valA.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.E_valA.setObjectName(_fromUtf8("E_valA"))
        self.gridLayout_5.addWidget(self.E_valA, 1, 4, 1, 1)
        self.E_srcA = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.E_srcA.sizePolicy().hasHeightForWidth())
        self.E_srcA.setSizePolicy(sizePolicy)
        self.E_srcA.setMinimumSize(QtCore.QSize(0, 20))
        self.E_srcA.setMaximumSize(QtCore.QSize(20, 24))
        self.E_srcA.setBaseSize(QtCore.QSize(70, 20))
        self.E_srcA.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.E_srcA.setObjectName(_fromUtf8("E_srcA"))
        self.gridLayout_5.addWidget(self.E_srcA, 1, 9, 1, 1)
        self.E_srcB = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.E_srcB.sizePolicy().hasHeightForWidth())
        self.E_srcB.setSizePolicy(sizePolicy)
        self.E_srcB.setMinimumSize(QtCore.QSize(0, 20))
        self.E_srcB.setMaximumSize(QtCore.QSize(20, 24))
        self.E_srcB.setBaseSize(QtCore.QSize(70, 20))
        self.E_srcB.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.E_srcB.setObjectName(_fromUtf8("E_srcB"))
        self.gridLayout_5.addWidget(self.E_srcB, 1, 10, 1, 1)
        self.label_33 = QtGui.QLabel(self.layoutWidget_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_5.addWidget(self.label_33, 0, 10, 1, 1)
        self.textBrowser_49 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_49.sizePolicy().hasHeightForWidth())
        self.textBrowser_49.setSizePolicy(sizePolicy)
        self.textBrowser_49.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_49.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_49.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_49.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_49.setObjectName(_fromUtf8("textBrowser_49"))
        self.gridLayout_5.addWidget(self.textBrowser_49, 2, 10, 1, 1)
        self.label_44 = QtGui.QLabel(self.layoutWidget_3)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_5.addWidget(self.label_44, 0, 0, 1, 1)
        self.E_stat = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.E_stat.sizePolicy().hasHeightForWidth())
        self.E_stat.setSizePolicy(sizePolicy)
        self.E_stat.setMinimumSize(QtCore.QSize(0, 20))
        self.E_stat.setMaximumSize(QtCore.QSize(40, 24))
        self.E_stat.setBaseSize(QtCore.QSize(70, 20))
        self.E_stat.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.E_stat.setObjectName(_fromUtf8("E_stat"))
        self.gridLayout_5.addWidget(self.E_stat, 1, 0, 1, 1)
        self.textBrowser_35 = QtGui.QTextBrowser(Y86Simulator)
        self.textBrowser_35.setGeometry(QtCore.QRect(30, 280, 481, 3))
        self.textBrowser_35.setMaximumSize(QtCore.QSize(16777215, 3))
        self.textBrowser_35.setStyleSheet(_fromUtf8("background:rgb(0, 0, 0)"))
        self.textBrowser_35.setObjectName(_fromUtf8("textBrowser_35"))
        self.layoutWidget_4 = QtGui.QWidget(Y86Simulator)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 380, 431, 75))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.D_valP = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.D_valP.sizePolicy().hasHeightForWidth())
        self.D_valP.setSizePolicy(sizePolicy)
        self.D_valP.setMinimumSize(QtCore.QSize(70, 20))
        self.D_valP.setMaximumSize(QtCore.QSize(70, 24))
        self.D_valP.setBaseSize(QtCore.QSize(70, 20))
        self.D_valP.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.D_valP.setObjectName(_fromUtf8("D_valP"))
        self.gridLayout_6.addWidget(self.D_valP, 1, 8, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(58, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 6, 1, 1)
        self.D_rA = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.D_rA.sizePolicy().hasHeightForWidth())
        self.D_rA.setSizePolicy(sizePolicy)
        self.D_rA.setMinimumSize(QtCore.QSize(0, 20))
        self.D_rA.setMaximumSize(QtCore.QSize(20, 24))
        self.D_rA.setBaseSize(QtCore.QSize(70, 20))
        self.D_rA.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.D_rA.setObjectName(_fromUtf8("D_rA"))
        self.gridLayout_6.addWidget(self.D_rA, 1, 4, 1, 1)
        self.D_rB = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.D_rB.sizePolicy().hasHeightForWidth())
        self.D_rB.setSizePolicy(sizePolicy)
        self.D_rB.setMinimumSize(QtCore.QSize(0, 20))
        self.D_rB.setMaximumSize(QtCore.QSize(20, 24))
        self.D_rB.setBaseSize(QtCore.QSize(70, 20))
        self.D_rB.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.D_rB.setObjectName(_fromUtf8("D_rB"))
        self.gridLayout_6.addWidget(self.D_rB, 1, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(58, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 3, 1, 1)
        self.textBrowser_54 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_54.sizePolicy().hasHeightForWidth())
        self.textBrowser_54.setSizePolicy(sizePolicy)
        self.textBrowser_54.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_54.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_54.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_54.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_54.setObjectName(_fromUtf8("textBrowser_54"))
        self.gridLayout_6.addWidget(self.textBrowser_54, 2, 4, 1, 1)
        self.textBrowser_55 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_55.sizePolicy().hasHeightForWidth())
        self.textBrowser_55.setSizePolicy(sizePolicy)
        self.textBrowser_55.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_55.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_55.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_55.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_55.setObjectName(_fromUtf8("textBrowser_55"))
        self.gridLayout_6.addWidget(self.textBrowser_55, 2, 5, 1, 1)
        self.label_40 = QtGui.QLabel(self.layoutWidget_4)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_6.addWidget(self.label_40, 0, 5, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget_4)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_6.addWidget(self.label_34, 0, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.layoutWidget_4)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_6.addWidget(self.label_39, 0, 4, 1, 1)
        self.label_36 = QtGui.QLabel(self.layoutWidget_4)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_6.addWidget(self.label_36, 0, 8, 1, 1)
        self.D_icode = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.D_icode.sizePolicy().hasHeightForWidth())
        self.D_icode.setSizePolicy(sizePolicy)
        self.D_icode.setMinimumSize(QtCore.QSize(0, 20))
        self.D_icode.setMaximumSize(QtCore.QSize(20, 24))
        self.D_icode.setBaseSize(QtCore.QSize(70, 20))
        self.D_icode.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.D_icode.setObjectName(_fromUtf8("D_icode"))
        self.gridLayout_6.addWidget(self.D_icode, 1, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.layoutWidget_4)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_6.addWidget(self.label_35, 0, 7, 1, 1)
        self.D_valC = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.D_valC.sizePolicy().hasHeightForWidth())
        self.D_valC.setSizePolicy(sizePolicy)
        self.D_valC.setMinimumSize(QtCore.QSize(70, 20))
        self.D_valC.setMaximumSize(QtCore.QSize(70, 24))
        self.D_valC.setBaseSize(QtCore.QSize(70, 20))
        self.D_valC.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.D_valC.setObjectName(_fromUtf8("D_valC"))
        self.gridLayout_6.addWidget(self.D_valC, 1, 7, 1, 1)
        self.label_38 = QtGui.QLabel(self.layoutWidget_4)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 0, 2, 1, 1)
        self.textBrowser_53 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_53.sizePolicy().hasHeightForWidth())
        self.textBrowser_53.setSizePolicy(sizePolicy)
        self.textBrowser_53.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_53.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_53.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_53.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_53.setObjectName(_fromUtf8("textBrowser_53"))
        self.gridLayout_6.addWidget(self.textBrowser_53, 2, 1, 1, 1)
        self.D_ifun = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.D_ifun.sizePolicy().hasHeightForWidth())
        self.D_ifun.setSizePolicy(sizePolicy)
        self.D_ifun.setMinimumSize(QtCore.QSize(0, 20))
        self.D_ifun.setMaximumSize(QtCore.QSize(20, 24))
        self.D_ifun.setBaseSize(QtCore.QSize(70, 20))
        self.D_ifun.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.D_ifun.setObjectName(_fromUtf8("D_ifun"))
        self.gridLayout_6.addWidget(self.D_ifun, 1, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.layoutWidget_4)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_6.addWidget(self.label_45, 0, 0, 1, 1)
        self.D_stat = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.D_stat.sizePolicy().hasHeightForWidth())
        self.D_stat.setSizePolicy(sizePolicy)
        self.D_stat.setMinimumSize(QtCore.QSize(0, 20))
        self.D_stat.setMaximumSize(QtCore.QSize(40, 24))
        self.D_stat.setBaseSize(QtCore.QSize(70, 20))
        self.D_stat.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.D_stat.setObjectName(_fromUtf8("D_stat"))
        self.gridLayout_6.addWidget(self.D_stat, 1, 0, 1, 1)
        self.layoutWidget_5 = QtGui.QWidget(Y86Simulator)
        self.layoutWidget_5.setGeometry(QtCore.QRect(30, 470, 141, 51))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_43 = QtGui.QLabel(self.layoutWidget_5)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_7.addWidget(self.label_43, 0, 1, 1, 1)
        self.F_predPC = QtGui.QTextBrowser(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.F_predPC.sizePolicy().hasHeightForWidth())
        self.F_predPC.setSizePolicy(sizePolicy)
        self.F_predPC.setMinimumSize(QtCore.QSize(70, 20))
        self.F_predPC.setMaximumSize(QtCore.QSize(70, 24))
        self.F_predPC.setBaseSize(QtCore.QSize(70, 20))
        self.F_predPC.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.F_predPC.setObjectName(_fromUtf8("F_predPC"))
        self.gridLayout_7.addWidget(self.F_predPC, 1, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.layoutWidget_5)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_7.addWidget(self.label_46, 0, 0, 1, 1)
        self.F_stat = QtGui.QTextBrowser(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.F_stat.sizePolicy().hasHeightForWidth())
        self.F_stat.setSizePolicy(sizePolicy)
        self.F_stat.setMinimumSize(QtCore.QSize(0, 20))
        self.F_stat.setMaximumSize(QtCore.QSize(40, 24))
        self.F_stat.setBaseSize(QtCore.QSize(70, 20))
        self.F_stat.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.F_stat.setObjectName(_fromUtf8("F_stat"))
        self.gridLayout_7.addWidget(self.F_stat, 1, 0, 1, 1)
        self.textBrowser_50 = QtGui.QTextBrowser(Y86Simulator)
        self.textBrowser_50.setGeometry(QtCore.QRect(30, 370, 481, 3))
        self.textBrowser_50.setMaximumSize(QtCore.QSize(16777215, 3))
        self.textBrowser_50.setStyleSheet(_fromUtf8("background:rgb(0, 0, 0)"))
        self.textBrowser_50.setObjectName(_fromUtf8("textBrowser_50"))
        self.textBrowser_56 = QtGui.QTextBrowser(Y86Simulator)
        self.textBrowser_56.setGeometry(QtCore.QRect(30, 460, 481, 3))
        self.textBrowser_56.setMaximumSize(QtCore.QSize(16777215, 3))
        self.textBrowser_56.setStyleSheet(_fromUtf8("background:rgb(0, 0, 0)"))
        self.textBrowser_56.setObjectName(_fromUtf8("textBrowser_56"))
        self.loadButton = QtGui.QPushButton(Y86Simulator)
        self.loadButton.setGeometry(QtCore.QRect(414, 20, 111, 23))
        self.loadButton.setDefault(False)
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.label_7 = QtGui.QLabel(Y86Simulator)
        self.label_7.setGeometry(QtCore.QRect(60, 70, 54, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Code = QtGui.QTextBrowser(Y86Simulator)
        self.Code.setGeometry(QtCore.QRect(570, 110, 351, 171))
        self.Code.setObjectName(_fromUtf8("Code"))
        self.frequency = QtGui.QLineEdit(Y86Simulator)
        self.frequency.setGeometry(QtCore.QRect(300, 70, 113, 20))
        self.frequency.setStyleSheet(_fromUtf8("border:white\n"
""))
        self.frequency.setObjectName(_fromUtf8("frequency"))
        self.saveButton = QtGui.QPushButton(Y86Simulator)
        self.saveButton.setGeometry(QtCore.QRect(414, 60, 111, 23))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.saveAdd = QtGui.QLineEdit(Y86Simulator)
        self.saveAdd.setGeometry(QtCore.QRect(530, 60, 371, 21))
        self.saveAdd.setObjectName(_fromUtf8("saveAdd"))
        self.begin = QtGui.QPushButton(Y86Simulator)
        self.begin.setGeometry(QtCore.QRect(330, 20, 75, 23))
        self.begin.setObjectName(_fromUtf8("begin"))
        self.label_8 = QtGui.QLabel(Y86Simulator)
        self.label_8.setGeometry(QtCore.QRect(570, 380, 54, 12))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Y86Simulator)
        self.label_9.setGeometry(QtCore.QRect(570, 410, 54, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(Y86Simulator)
        self.label_10.setGeometry(QtCore.QRect(570, 440, 54, 12))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Y86Simulator)
        self.label_11.setGeometry(QtCore.QRect(570, 470, 54, 12))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_18 = QtGui.QLabel(Y86Simulator)
        self.label_18.setGeometry(QtCore.QRect(730, 380, 54, 12))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(Y86Simulator)
        self.label_19.setGeometry(QtCore.QRect(730, 410, 54, 12))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(Y86Simulator)
        self.label_20.setGeometry(QtCore.QRect(730, 440, 54, 12))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(Y86Simulator)
        self.label_21.setGeometry(QtCore.QRect(730, 470, 54, 12))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.eax = QtGui.QLineEdit(Y86Simulator)
        self.eax.setGeometry(QtCore.QRect(600, 380, 113, 20))
        self.eax.setObjectName(_fromUtf8("eax"))
        self.ebx = QtGui.QLineEdit(Y86Simulator)
        self.ebx.setGeometry(QtCore.QRect(600, 410, 113, 20))
        self.ebx.setObjectName(_fromUtf8("ebx"))
        self.ecx = QtGui.QLineEdit(Y86Simulator)
        self.ecx.setGeometry(QtCore.QRect(600, 440, 113, 20))
        self.ecx.setObjectName(_fromUtf8("ecx"))
        self.edx = QtGui.QLineEdit(Y86Simulator)
        self.edx.setGeometry(QtCore.QRect(600, 470, 113, 20))
        self.edx.setObjectName(_fromUtf8("edx"))
        self.esi = QtGui.QLineEdit(Y86Simulator)
        self.esi.setGeometry(QtCore.QRect(760, 380, 113, 20))
        self.esi.setObjectName(_fromUtf8("esi"))
        self.edi = QtGui.QLineEdit(Y86Simulator)
        self.edi.setGeometry(QtCore.QRect(760, 410, 113, 20))
        self.edi.setObjectName(_fromUtf8("edi"))
        self.esp = QtGui.QLineEdit(Y86Simulator)
        self.esp.setGeometry(QtCore.QRect(760, 440, 113, 20))
        self.esp.setObjectName(_fromUtf8("esp"))
        self.ebp = QtGui.QLineEdit(Y86Simulator)
        self.ebp.setGeometry(QtCore.QRect(760, 470, 113, 20))
        self.ebp.setObjectName(_fromUtf8("ebp"))
        self.label_22 = QtGui.QLabel(Y86Simulator)
        self.label_22.setGeometry(QtCore.QRect(720, 330, 54, 12))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.cycle = QtGui.QLineEdit(Y86Simulator)
        self.cycle.setGeometry(QtCore.QRect(790, 330, 113, 20))
        self.cycle.setObjectName(_fromUtf8("cycle"))
        self.label_23 = QtGui.QLabel(Y86Simulator)
        self.label_23.setGeometry(QtCore.QRect(570, 520, 54, 12))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.ZF = QtGui.QLineEdit(Y86Simulator)
        self.ZF.setGeometry(QtCore.QRect(590, 520, 41, 20))
        self.ZF.setObjectName(_fromUtf8("ZF"))
        self.label_24 = QtGui.QLabel(Y86Simulator)
        self.label_24.setGeometry(QtCore.QRect(640, 520, 54, 12))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.SF = QtGui.QLineEdit(Y86Simulator)
        self.SF.setGeometry(QtCore.QRect(660, 520, 41, 20))
        self.SF.setObjectName(_fromUtf8("SF"))
        self.label_37 = QtGui.QLabel(Y86Simulator)
        self.label_37.setGeometry(QtCore.QRect(710, 520, 54, 12))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.OF = QtGui.QLineEdit(Y86Simulator)
        self.OF.setGeometry(QtCore.QRect(730, 520, 41, 20))
        self.OF.setObjectName(_fromUtf8("OF"))
        self.textBrowser_26 = QtGui.QTextBrowser(Y86Simulator)
        self.textBrowser_26.setGeometry(QtCore.QRect(32, 192, 482, 3))
        self.textBrowser_26.setMaximumSize(QtCore.QSize(16777215, 3))
        self.textBrowser_26.setStyleSheet(_fromUtf8("background:rgb(0, 0, 0)"))
        self.textBrowser_26.setObjectName(_fromUtf8("textBrowser_26"))
        self.layoutWidget = QtGui.QWidget(Y86Simulator)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 200, 501, 74))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 6, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 0, 4, 1, 1)
        self.M_valE = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.M_valE.sizePolicy().hasHeightForWidth())
        self.M_valE.setSizePolicy(sizePolicy)
        self.M_valE.setMinimumSize(QtCore.QSize(70, 20))
        self.M_valE.setMaximumSize(QtCore.QSize(70, 24))
        self.M_valE.setBaseSize(QtCore.QSize(70, 20))
        self.M_valE.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.M_valE.setObjectName(_fromUtf8("M_valE"))
        self.gridLayout_3.addWidget(self.M_valE, 1, 4, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 0, 8, 1, 1)
        self.M_valA = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.M_valA.sizePolicy().hasHeightForWidth())
        self.M_valA.setSizePolicy(sizePolicy)
        self.M_valA.setMinimumSize(QtCore.QSize(70, 20))
        self.M_valA.setMaximumSize(QtCore.QSize(70, 24))
        self.M_valA.setBaseSize(QtCore.QSize(70, 20))
        self.M_valA.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.M_valA.setObjectName(_fromUtf8("M_valA"))
        self.gridLayout_3.addWidget(self.M_valA, 1, 5, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 2, 1, 1)
        self.textBrowser_24 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_24.sizePolicy().hasHeightForWidth())
        self.textBrowser_24.setSizePolicy(sizePolicy)
        self.textBrowser_24.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_24.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_24.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_24.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_24.setObjectName(_fromUtf8("textBrowser_24"))
        self.gridLayout_3.addWidget(self.textBrowser_24, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 5, 1, 1)
        self.M_dstE = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.M_dstE.sizePolicy().hasHeightForWidth())
        self.M_dstE.setSizePolicy(sizePolicy)
        self.M_dstE.setMinimumSize(QtCore.QSize(0, 20))
        self.M_dstE.setMaximumSize(QtCore.QSize(20, 24))
        self.M_dstE.setBaseSize(QtCore.QSize(70, 20))
        self.M_dstE.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.M_dstE.setObjectName(_fromUtf8("M_dstE"))
        self.gridLayout_3.addWidget(self.M_dstE, 1, 7, 1, 1)
        self.textBrowser_18 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_18.sizePolicy().hasHeightForWidth())
        self.textBrowser_18.setSizePolicy(sizePolicy)
        self.textBrowser_18.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_18.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_18.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_18.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_18.setObjectName(_fromUtf8("textBrowser_18"))
        self.gridLayout_3.addWidget(self.textBrowser_18, 2, 7, 1, 1)
        self.textBrowser_15 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_15.sizePolicy().hasHeightForWidth())
        self.textBrowser_15.setSizePolicy(sizePolicy)
        self.textBrowser_15.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_15.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_15.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_15.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_15.setObjectName(_fromUtf8("textBrowser_15"))
        self.gridLayout_3.addWidget(self.textBrowser_15, 2, 8, 1, 1)
        self.M_bch = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.M_bch.sizePolicy().hasHeightForWidth())
        self.M_bch.setSizePolicy(sizePolicy)
        self.M_bch.setMinimumSize(QtCore.QSize(0, 20))
        self.M_bch.setMaximumSize(QtCore.QSize(20, 24))
        self.M_bch.setBaseSize(QtCore.QSize(70, 20))
        self.M_bch.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.M_bch.setObjectName(_fromUtf8("M_bch"))
        self.gridLayout_3.addWidget(self.M_bch, 1, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 7, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 1, 1, 1)
        self.M_dstM = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.M_dstM.sizePolicy().hasHeightForWidth())
        self.M_dstM.setSizePolicy(sizePolicy)
        self.M_dstM.setMinimumSize(QtCore.QSize(0, 20))
        self.M_dstM.setMaximumSize(QtCore.QSize(20, 24))
        self.M_dstM.setBaseSize(QtCore.QSize(70, 20))
        self.M_dstM.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.M_dstM.setObjectName(_fromUtf8("M_dstM"))
        self.gridLayout_3.addWidget(self.M_dstM, 1, 8, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(58, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 3, 1, 1)
        self.M_icode = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.M_icode.sizePolicy().hasHeightForWidth())
        self.M_icode.setSizePolicy(sizePolicy)
        self.M_icode.setMinimumSize(QtCore.QSize(0, 20))
        self.M_icode.setMaximumSize(QtCore.QSize(20, 24))
        self.M_icode.setBaseSize(QtCore.QSize(70, 20))
        self.M_icode.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.M_icode.setObjectName(_fromUtf8("M_icode"))
        self.gridLayout_3.addWidget(self.M_icode, 1, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.layoutWidget)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_3.addWidget(self.label_42, 0, 0, 1, 1)
        self.M_stat = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.M_stat.sizePolicy().hasHeightForWidth())
        self.M_stat.setSizePolicy(sizePolicy)
        self.M_stat.setMinimumSize(QtCore.QSize(0, 20))
        self.M_stat.setMaximumSize(QtCore.QSize(40, 24))
        self.M_stat.setBaseSize(QtCore.QSize(70, 20))
        self.M_stat.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.M_stat.setObjectName(_fromUtf8("M_stat"))
        self.gridLayout_3.addWidget(self.M_stat, 1, 0, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(Y86Simulator)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 110, 501, 74))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.W_icode = QtGui.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.W_icode.sizePolicy().hasHeightForWidth())
        self.W_icode.setSizePolicy(sizePolicy)
        self.W_icode.setMinimumSize(QtCore.QSize(0, 20))
        self.W_icode.setMaximumSize(QtCore.QSize(20, 24))
        self.W_icode.setBaseSize(QtCore.QSize(70, 20))
        self.W_icode.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.W_icode.setObjectName(_fromUtf8("W_icode"))
        self.gridLayout.addWidget(self.W_icode, 1, 1, 1, 1)
        self.W_valM = QtGui.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.W_valM.sizePolicy().hasHeightForWidth())
        self.W_valM.setSizePolicy(sizePolicy)
        self.W_valM.setMinimumSize(QtCore.QSize(70, 20))
        self.W_valM.setMaximumSize(QtCore.QSize(70, 24))
        self.W_valM.setBaseSize(QtCore.QSize(70, 20))
        self.W_valM.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.W_valM.setObjectName(_fromUtf8("W_valM"))
        self.gridLayout.addWidget(self.W_valM, 1, 4, 1, 1)
        self.W_valE = QtGui.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.W_valE.sizePolicy().hasHeightForWidth())
        self.W_valE.setSizePolicy(sizePolicy)
        self.W_valE.setMinimumSize(QtCore.QSize(70, 20))
        self.W_valE.setMaximumSize(QtCore.QSize(70, 24))
        self.W_valE.setBaseSize(QtCore.QSize(70, 20))
        self.W_valE.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.W_valE.setObjectName(_fromUtf8("W_valE"))
        self.gridLayout.addWidget(self.W_valE, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 7, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(78, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        self.W_dstM = QtGui.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.W_dstM.sizePolicy().hasHeightForWidth())
        self.W_dstM.setSizePolicy(sizePolicy)
        self.W_dstM.setMinimumSize(QtCore.QSize(0, 20))
        self.W_dstM.setMaximumSize(QtCore.QSize(20, 24))
        self.W_dstM.setBaseSize(QtCore.QSize(70, 20))
        self.W_dstM.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.W_dstM.setObjectName(_fromUtf8("W_dstM"))
        self.gridLayout.addWidget(self.W_dstM, 1, 7, 1, 1)
        self.textBrowser_5 = QtGui.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_5.sizePolicy().hasHeightForWidth())
        self.textBrowser_5.setSizePolicy(sizePolicy)
        self.textBrowser_5.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_5.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_5.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_5.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_5.setObjectName(_fromUtf8("textBrowser_5"))
        self.gridLayout.addWidget(self.textBrowser_5, 2, 7, 1, 1)
        self.W_dstE = QtGui.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.W_dstE.sizePolicy().hasHeightForWidth())
        self.W_dstE.setSizePolicy(sizePolicy)
        self.W_dstE.setMinimumSize(QtCore.QSize(0, 20))
        self.W_dstE.setMaximumSize(QtCore.QSize(20, 24))
        self.W_dstE.setBaseSize(QtCore.QSize(70, 20))
        self.W_dstE.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.W_dstE.setObjectName(_fromUtf8("W_dstE"))
        self.gridLayout.addWidget(self.W_dstE, 1, 6, 1, 1)
        self.textBrowser_4 = QtGui.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_4.sizePolicy().hasHeightForWidth())
        self.textBrowser_4.setSizePolicy(sizePolicy)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_4.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_4.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.gridLayout.addWidget(self.textBrowser_4, 2, 6, 1, 1)
        self.label_41 = QtGui.QLabel(self.layoutWidget1)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout.addWidget(self.label_41, 0, 0, 1, 1)
        self.W_stat = QtGui.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.W_stat.sizePolicy().hasHeightForWidth())
        self.W_stat.setSizePolicy(sizePolicy)
        self.W_stat.setMinimumSize(QtCore.QSize(0, 20))
        self.W_stat.setMaximumSize(QtCore.QSize(40, 24))
        self.W_stat.setBaseSize(QtCore.QSize(70, 20))
        self.W_stat.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.W_stat.setObjectName(_fromUtf8("W_stat"))
        self.gridLayout.addWidget(self.W_stat, 1, 0, 1, 1)
        self.textBrowser_25 = QtGui.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_25.sizePolicy().hasHeightForWidth())
        self.textBrowser_25.setSizePolicy(sizePolicy)
        self.textBrowser_25.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_25.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_25.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_25.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_25.setObjectName(_fromUtf8("textBrowser_25"))
        self.gridLayout.addWidget(self.textBrowser_25, 2, 1, 1, 1)

        self.retranslateUi(Y86Simulator)
        QtCore.QMetaObject.connectSlotsByName(Y86Simulator)

    def retranslateUi(self, Y86Simulator):
        Y86Simulator.setWindowTitle(_translate("Y86Simulator", "Y86 Simulator", None))
        self.label.setText(_translate("Y86Simulator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Harrington\'; font-size:14pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600; font-style:normal; color:#ff557f;\">Y86 Simulator</span></p></body></html>", None))
        self.runButton.setText(_translate("Y86Simulator", "Run", None))
        self.pauseButton.setText(_translate("Y86Simulator", "Pause", None))
        self.stepButton.setText(_translate("Y86Simulator", "Step", None))
        self.backButton.setText(_translate("Y86Simulator", "Back", None))
        self.resetButton.setText(_translate("Y86Simulator", "Reset", None))
        self.label_32.setText(_translate("Y86Simulator", "srcA", None))
        self.label_31.setText(_translate("Y86Simulator", "valA", None))
        self.label_30.setText(_translate("Y86Simulator", "valC", None))
        self.label_26.setText(_translate("Y86Simulator", "iFun", None))
        self.label_25.setText(_translate("Y86Simulator", "dstM", None))
        self.label_27.setText(_translate("Y86Simulator", "valB", None))
        self.label_28.setText(_translate("Y86Simulator", "dstE", None))
        self.label_29.setText(_translate("Y86Simulator", "iCode", None))
        self.label_33.setText(_translate("Y86Simulator", "srcB", None))
        self.label_44.setText(_translate("Y86Simulator", "E_stat", None))
        self.label_40.setText(_translate("Y86Simulator", "rB", None))
        self.label_34.setText(_translate("Y86Simulator", "iCode", None))
        self.label_39.setText(_translate("Y86Simulator", "rA", None))
        self.label_36.setText(_translate("Y86Simulator", "valP", None))
        self.label_35.setText(_translate("Y86Simulator", "valC", None))
        self.label_38.setText(_translate("Y86Simulator", "iFun", None))
        self.label_45.setText(_translate("Y86Simulator", "D_stat", None))
        self.label_43.setText(_translate("Y86Simulator", "predPC", None))
        self.label_46.setText(_translate("Y86Simulator", "F_stat", None))
        self.loadButton.setText(_translate("Y86Simulator", "Choose Open File", None))
        self.label_7.setText(_translate("Y86Simulator", "interval", None))
        self.saveButton.setText(_translate("Y86Simulator", "Choose Save File", None))
        self.begin.setText(_translate("Y86Simulator", "Load", None))
        self.label_8.setText(_translate("Y86Simulator", "%eax", None))
        self.label_9.setText(_translate("Y86Simulator", "%ebx", None))
        self.label_10.setText(_translate("Y86Simulator", "%ecx", None))
        self.label_11.setText(_translate("Y86Simulator", "%edx", None))
        self.label_18.setText(_translate("Y86Simulator", "%esi", None))
        self.label_19.setText(_translate("Y86Simulator", "%edi", None))
        self.label_20.setText(_translate("Y86Simulator", "%esp", None))
        self.label_21.setText(_translate("Y86Simulator", "%ebp", None))
        self.label_22.setText(_translate("Y86Simulator", "cycles", None))
        self.label_23.setText(_translate("Y86Simulator", "ZF", None))
        self.label_24.setText(_translate("Y86Simulator", "SF", None))
        self.label_37.setText(_translate("Y86Simulator", "OF", None))
        self.label_16.setText(_translate("Y86Simulator", "valE", None))
        self.label_15.setText(_translate("Y86Simulator", "dstM", None))
        self.label_17.setText(_translate("Y86Simulator", "Bch", None))
        self.label_12.setText(_translate("Y86Simulator", "valA", None))
        self.label_14.setText(_translate("Y86Simulator", "dstE", None))
        self.label_13.setText(_translate("Y86Simulator", "iCode", None))
        self.label_42.setText(_translate("Y86Simulator", "M_stat", None))
        self.label_2.setText(_translate("Y86Simulator", "iCode", None))
        self.label_4.setText(_translate("Y86Simulator", "valM", None))
        self.label_5.setText(_translate("Y86Simulator", "dstE", None))
        self.label_6.setText(_translate("Y86Simulator", "dstM", None))
        self.label_3.setText(_translate("Y86Simulator", "valE", None))
        self.label_41.setText(_translate("Y86Simulator", "W_stat", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Y86Simulator = QtGui.QDialog()
    ui = Ui_Y86Simulator()
    ui.setupUi(Y86Simulator)
    Y86Simulator.show()
    sys.exit(app.exec_())

