# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\FDU\workspace\GUI\Y86\y86.ui'
#
# Created: Tue Jun 11 17:49:34 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Y86Simulator(object):
    def setupUi(self, Y86Simulator):
        Y86Simulator.setObjectName(_fromUtf8("Y86Simulator"))
        Y86Simulator.resize(918, 639)
        Y86Simulator.setStyleSheet(_fromUtf8("QDialog\n"
"{\n"
"background:white;\n"
"}\n"
"QTextBrowser\n"
"{\n"
"border:white;\n"
"}"))
        self.label = QtGui.QLabel(Y86Simulator)
        self.label.setGeometry(QtCore.QRect(30, 20, 201, 31))
        self.label.setStyleSheet(_fromUtf8("font-family:Times;\n"
"font: italic 14pt \"Harrington\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.layoutWidget_2 = QtGui.QWidget(Y86Simulator)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 540, 482, 25))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.runButton = QtGui.QPushButton(self.layoutWidget_2)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.horizontalLayout.addWidget(self.runButton)
        self.stopButton = QtGui.QPushButton(self.layoutWidget_2)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout.addWidget(self.stopButton)
        self.stepButton = QtGui.QPushButton(self.layoutWidget_2)
        self.stepButton.setObjectName(_fromUtf8("stepButton"))
        self.horizontalLayout.addWidget(self.stepButton)
        self.backButton = QtGui.QPushButton(self.layoutWidget_2)
        self.backButton.setObjectName(_fromUtf8("backButton"))
        self.horizontalLayout.addWidget(self.backButton)
        self.resetButton = QtGui.QPushButton(self.layoutWidget_2)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.horizontalLayout.addWidget(self.resetButton)
        self.loadAdd = QtGui.QLineEdit(Y86Simulator)
        self.loadAdd.setGeometry(QtCore.QRect(530, 20, 371, 21))
        self.loadAdd.setObjectName(_fromUtf8("loadAdd"))
        self.Slider = QtGui.QSlider(Y86Simulator)
        self.Slider.setGeometry(QtCore.QRect(130, 70, 160, 22))
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName(_fromUtf8("Slider"))
        self.layoutWidget_3 = QtGui.QWidget(Y86Simulator)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 290, 610, 74))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.textBrowser_42 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_42.sizePolicy().hasHeightForWidth())
        self.textBrowser_42.setSizePolicy(sizePolicy)
        self.textBrowser_42.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_42.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_42.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_42.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_42.setObjectName(_fromUtf8("textBrowser_42"))
        self.gridLayout_5.addWidget(self.textBrowser_42, 1, 7, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 0, 0, 1, 1)
        self.textBrowser_43 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_43.sizePolicy().hasHeightForWidth())
        self.textBrowser_43.setSizePolicy(sizePolicy)
        self.textBrowser_43.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_43.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_43.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_43.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_43.setObjectName(_fromUtf8("textBrowser_43"))
        self.gridLayout_5.addWidget(self.textBrowser_43, 1, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_5.addWidget(self.label_30, 0, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget_3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 0, 3, 1, 1)
        self.textBrowser_45 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_45.sizePolicy().hasHeightForWidth())
        self.textBrowser_45.setSizePolicy(sizePolicy)
        self.textBrowser_45.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_45.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_45.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_45.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_45.setObjectName(_fromUtf8("textBrowser_45"))
        self.gridLayout_5.addWidget(self.textBrowser_45, 1, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 0, 7, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 0, 1, 1, 1)
        self.textBrowser_37 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_37.sizePolicy().hasHeightForWidth())
        self.textBrowser_37.setSizePolicy(sizePolicy)
        self.textBrowser_37.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_37.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_37.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_37.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_37.setObjectName(_fromUtf8("textBrowser_37"))
        self.gridLayout_5.addWidget(self.textBrowser_37, 2, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.layoutWidget_3)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_5.addWidget(self.label_27, 0, 4, 1, 1)
        self.textBrowser_38 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_38.sizePolicy().hasHeightForWidth())
        self.textBrowser_38.setSizePolicy(sizePolicy)
        self.textBrowser_38.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_38.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_38.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_38.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_38.setObjectName(_fromUtf8("textBrowser_38"))
        self.gridLayout_5.addWidget(self.textBrowser_38, 1, 6, 1, 1)
        self.textBrowser_39 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_39.sizePolicy().hasHeightForWidth())
        self.textBrowser_39.setSizePolicy(sizePolicy)
        self.textBrowser_39.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_39.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_39.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_39.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_39.setObjectName(_fromUtf8("textBrowser_39"))
        self.gridLayout_5.addWidget(self.textBrowser_39, 2, 6, 1, 1)
        self.textBrowser_40 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_40.sizePolicy().hasHeightForWidth())
        self.textBrowser_40.setSizePolicy(sizePolicy)
        self.textBrowser_40.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_40.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_40.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_40.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_40.setObjectName(_fromUtf8("textBrowser_40"))
        self.gridLayout_5.addWidget(self.textBrowser_40, 2, 7, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_5.addWidget(self.label_28, 0, 6, 1, 1)
        self.textBrowser_41 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_41.sizePolicy().hasHeightForWidth())
        self.textBrowser_41.setSizePolicy(sizePolicy)
        self.textBrowser_41.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_41.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_41.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_41.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_41.setObjectName(_fromUtf8("textBrowser_41"))
        self.gridLayout_5.addWidget(self.textBrowser_41, 1, 1, 1, 1)
        self.textBrowser_47 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_47.sizePolicy().hasHeightForWidth())
        self.textBrowser_47.setSizePolicy(sizePolicy)
        self.textBrowser_47.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_47.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_47.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_47.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_47.setObjectName(_fromUtf8("textBrowser_47"))
        self.gridLayout_5.addWidget(self.textBrowser_47, 2, 8, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget_3)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_5.addWidget(self.label_32, 0, 8, 1, 1)
        spacerItem = QtGui.QSpacerItem(68, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 1, 5, 1, 1)
        self.textBrowser_36 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_36.sizePolicy().hasHeightForWidth())
        self.textBrowser_36.setSizePolicy(sizePolicy)
        self.textBrowser_36.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_36.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_36.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_36.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_36.setObjectName(_fromUtf8("textBrowser_36"))
        self.gridLayout_5.addWidget(self.textBrowser_36, 1, 4, 1, 1)
        self.textBrowser_44 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_44.sizePolicy().hasHeightForWidth())
        self.textBrowser_44.setSizePolicy(sizePolicy)
        self.textBrowser_44.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_44.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_44.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_44.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_44.setObjectName(_fromUtf8("textBrowser_44"))
        self.gridLayout_5.addWidget(self.textBrowser_44, 1, 3, 1, 1)
        self.textBrowser_46 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_46.sizePolicy().hasHeightForWidth())
        self.textBrowser_46.setSizePolicy(sizePolicy)
        self.textBrowser_46.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_46.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_46.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_46.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_46.setObjectName(_fromUtf8("textBrowser_46"))
        self.gridLayout_5.addWidget(self.textBrowser_46, 1, 8, 1, 1)
        self.textBrowser_48 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_48.sizePolicy().hasHeightForWidth())
        self.textBrowser_48.setSizePolicy(sizePolicy)
        self.textBrowser_48.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_48.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_48.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_48.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_48.setObjectName(_fromUtf8("textBrowser_48"))
        self.gridLayout_5.addWidget(self.textBrowser_48, 1, 9, 1, 1)
        self.textBrowser_49 = QtGui.QTextBrowser(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_49.sizePolicy().hasHeightForWidth())
        self.textBrowser_49.setSizePolicy(sizePolicy)
        self.textBrowser_49.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_49.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_49.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_49.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_49.setObjectName(_fromUtf8("textBrowser_49"))
        self.gridLayout_5.addWidget(self.textBrowser_49, 2, 9, 1, 1)
        self.label_33 = QtGui.QLabel(self.layoutWidget_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_5.addWidget(self.label_33, 0, 9, 1, 1)
        self.textBrowser_35 = QtGui.QTextBrowser(Y86Simulator)
        self.textBrowser_35.setGeometry(QtCore.QRect(30, 280, 481, 3))
        self.textBrowser_35.setMaximumSize(QtCore.QSize(16777215, 3))
        self.textBrowser_35.setStyleSheet(_fromUtf8("background:rgb(0, 0, 0)"))
        self.textBrowser_35.setObjectName(_fromUtf8("textBrowser_35"))
        self.layoutWidget_4 = QtGui.QWidget(Y86Simulator)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 380, 411, 75))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.textBrowser_58 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_58.sizePolicy().hasHeightForWidth())
        self.textBrowser_58.setSizePolicy(sizePolicy)
        self.textBrowser_58.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_58.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_58.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_58.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_58.setObjectName(_fromUtf8("textBrowser_58"))
        self.gridLayout_6.addWidget(self.textBrowser_58, 1, 3, 1, 1)
        self.textBrowser_59 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_59.sizePolicy().hasHeightForWidth())
        self.textBrowser_59.setSizePolicy(sizePolicy)
        self.textBrowser_59.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_59.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_59.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_59.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_59.setObjectName(_fromUtf8("textBrowser_59"))
        self.gridLayout_6.addWidget(self.textBrowser_59, 1, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(58, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 1, 2, 1, 1)
        self.textBrowser_54 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_54.sizePolicy().hasHeightForWidth())
        self.textBrowser_54.setSizePolicy(sizePolicy)
        self.textBrowser_54.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_54.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_54.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_54.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_54.setObjectName(_fromUtf8("textBrowser_54"))
        self.gridLayout_6.addWidget(self.textBrowser_54, 2, 3, 1, 1)
        self.textBrowser_55 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_55.sizePolicy().hasHeightForWidth())
        self.textBrowser_55.setSizePolicy(sizePolicy)
        self.textBrowser_55.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_55.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_55.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_55.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_55.setObjectName(_fromUtf8("textBrowser_55"))
        self.gridLayout_6.addWidget(self.textBrowser_55, 2, 4, 1, 1)
        self.label_39 = QtGui.QLabel(self.layoutWidget_4)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_6.addWidget(self.label_39, 0, 3, 1, 1)
        self.label_40 = QtGui.QLabel(self.layoutWidget_4)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_6.addWidget(self.label_40, 0, 4, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget_4)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_6.addWidget(self.label_34, 0, 0, 1, 1)
        self.textBrowser_51 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_51.sizePolicy().hasHeightForWidth())
        self.textBrowser_51.setSizePolicy(sizePolicy)
        self.textBrowser_51.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_51.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_51.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_51.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_51.setObjectName(_fromUtf8("textBrowser_51"))
        self.gridLayout_6.addWidget(self.textBrowser_51, 1, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.layoutWidget_4)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_6.addWidget(self.label_36, 0, 7, 1, 1)
        self.label_35 = QtGui.QLabel(self.layoutWidget_4)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_6.addWidget(self.label_35, 0, 6, 1, 1)
        self.textBrowser_52 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_52.sizePolicy().hasHeightForWidth())
        self.textBrowser_52.setSizePolicy(sizePolicy)
        self.textBrowser_52.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_52.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_52.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_52.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_52.setObjectName(_fromUtf8("textBrowser_52"))
        self.gridLayout_6.addWidget(self.textBrowser_52, 1, 6, 1, 1)
        self.label_38 = QtGui.QLabel(self.layoutWidget_4)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 0, 1, 1, 1)
        self.textBrowser_53 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_53.sizePolicy().hasHeightForWidth())
        self.textBrowser_53.setSizePolicy(sizePolicy)
        self.textBrowser_53.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_53.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_53.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_53.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_53.setObjectName(_fromUtf8("textBrowser_53"))
        self.gridLayout_6.addWidget(self.textBrowser_53, 2, 0, 1, 1)
        self.textBrowser_57 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_57.sizePolicy().hasHeightForWidth())
        self.textBrowser_57.setSizePolicy(sizePolicy)
        self.textBrowser_57.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_57.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_57.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_57.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_57.setObjectName(_fromUtf8("textBrowser_57"))
        self.gridLayout_6.addWidget(self.textBrowser_57, 1, 1, 1, 1)
        self.textBrowser_60 = QtGui.QTextBrowser(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_60.sizePolicy().hasHeightForWidth())
        self.textBrowser_60.setSizePolicy(sizePolicy)
        self.textBrowser_60.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_60.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_60.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_60.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_60.setObjectName(_fromUtf8("textBrowser_60"))
        self.gridLayout_6.addWidget(self.textBrowser_60, 1, 7, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(58, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 5, 1, 1)
        self.layoutWidget_5 = QtGui.QWidget(Y86Simulator)
        self.layoutWidget_5.setGeometry(QtCore.QRect(30, 470, 81, 51))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_43 = QtGui.QLabel(self.layoutWidget_5)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_7.addWidget(self.label_43, 0, 0, 1, 1)
        self.textBrowser_68 = QtGui.QTextBrowser(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_68.sizePolicy().hasHeightForWidth())
        self.textBrowser_68.setSizePolicy(sizePolicy)
        self.textBrowser_68.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_68.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_68.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_68.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_68.setObjectName(_fromUtf8("textBrowser_68"))
        self.gridLayout_7.addWidget(self.textBrowser_68, 1, 0, 1, 1)
        self.textBrowser_50 = QtGui.QTextBrowser(Y86Simulator)
        self.textBrowser_50.setGeometry(QtCore.QRect(30, 370, 481, 3))
        self.textBrowser_50.setMaximumSize(QtCore.QSize(16777215, 3))
        self.textBrowser_50.setStyleSheet(_fromUtf8("background:rgb(0, 0, 0)"))
        self.textBrowser_50.setObjectName(_fromUtf8("textBrowser_50"))
        self.textBrowser_56 = QtGui.QTextBrowser(Y86Simulator)
        self.textBrowser_56.setGeometry(QtCore.QRect(30, 460, 481, 3))
        self.textBrowser_56.setMaximumSize(QtCore.QSize(16777215, 3))
        self.textBrowser_56.setStyleSheet(_fromUtf8("background:rgb(0, 0, 0)"))
        self.textBrowser_56.setObjectName(_fromUtf8("textBrowser_56"))
        self.loadButton = QtGui.QPushButton(Y86Simulator)
        self.loadButton.setGeometry(QtCore.QRect(450, 20, 75, 23))
        self.loadButton.setDefault(False)
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.label_7 = QtGui.QLabel(Y86Simulator)
        self.label_7.setGeometry(QtCore.QRect(60, 70, 54, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Code = QtGui.QTextBrowser(Y86Simulator)
        self.Code.setGeometry(QtCore.QRect(520, 110, 351, 171))
        self.Code.setObjectName(_fromUtf8("Code"))
        self.frequency = QtGui.QLineEdit(Y86Simulator)
        self.frequency.setGeometry(QtCore.QRect(300, 70, 113, 20))
        self.frequency.setStyleSheet(_fromUtf8("border:white\n"
""))
        self.frequency.setObjectName(_fromUtf8("frequency"))
        self.layoutWidget = QtGui.QWidget(Y86Simulator)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 111, 484, 165))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textBrowser_7 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_7.sizePolicy().hasHeightForWidth())
        self.textBrowser_7.setSizePolicy(sizePolicy)
        self.textBrowser_7.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_7.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_7.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_7.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_7.setObjectName(_fromUtf8("textBrowser_7"))
        self.gridLayout.addWidget(self.textBrowser_7, 1, 6, 1, 1)
        self.textBrowser_5 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_5.sizePolicy().hasHeightForWidth())
        self.textBrowser_5.setSizePolicy(sizePolicy)
        self.textBrowser_5.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_5.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_5.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_5.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_5.setObjectName(_fromUtf8("textBrowser_5"))
        self.gridLayout.addWidget(self.textBrowser_5, 2, 6, 1, 1)
        self.textBrowser_6 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_6.sizePolicy().hasHeightForWidth())
        self.textBrowser_6.setSizePolicy(sizePolicy)
        self.textBrowser_6.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_6.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_6.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_6.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_6.setObjectName(_fromUtf8("textBrowser_6"))
        self.gridLayout.addWidget(self.textBrowser_6, 1, 5, 1, 1)
        self.textBrowser_4 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_4.sizePolicy().hasHeightForWidth())
        self.textBrowser_4.setSizePolicy(sizePolicy)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_4.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_4.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_4.setObjectName(_fromUtf8("textBrowser_4"))
        self.gridLayout.addWidget(self.textBrowser_4, 2, 5, 1, 1)
        self.W_icode = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.W_icode.sizePolicy().hasHeightForWidth())
        self.W_icode.setSizePolicy(sizePolicy)
        self.W_icode.setMinimumSize(QtCore.QSize(0, 20))
        self.W_icode.setMaximumSize(QtCore.QSize(20, 24))
        self.W_icode.setBaseSize(QtCore.QSize(70, 20))
        self.W_icode.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.W_icode.setObjectName(_fromUtf8("W_icode"))
        self.gridLayout.addWidget(self.W_icode, 1, 0, 1, 1)
        self.textBrowser_3 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_3.sizePolicy().hasHeightForWidth())
        self.textBrowser_3.setSizePolicy(sizePolicy)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_3.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_3.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_3.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.gridLayout.addWidget(self.textBrowser_3, 1, 3, 1, 1)
        self.textBrowser_2 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_2.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_2.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_2.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.gridLayout.addWidget(self.textBrowser_2, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 6, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 4, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(78, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 1, 1, 1)
        self.textBrowser_23 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_23.sizePolicy().hasHeightForWidth())
        self.textBrowser_23.setSizePolicy(sizePolicy)
        self.textBrowser_23.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_23.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_23.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_23.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_23.setObjectName(_fromUtf8("textBrowser_23"))
        self.gridLayout.addWidget(self.textBrowser_23, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.textBrowser_26 = QtGui.QTextBrowser(self.layoutWidget)
        self.textBrowser_26.setMaximumSize(QtCore.QSize(16777215, 3))
        self.textBrowser_26.setStyleSheet(_fromUtf8("background:rgb(0, 0, 0)"))
        self.textBrowser_26.setObjectName(_fromUtf8("textBrowser_26"))
        self.verticalLayout.addWidget(self.textBrowser_26)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 0, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 5, 1, 1)
        self.textBrowser_20 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_20.sizePolicy().hasHeightForWidth())
        self.textBrowser_20.setSizePolicy(sizePolicy)
        self.textBrowser_20.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_20.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_20.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_20.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_20.setObjectName(_fromUtf8("textBrowser_20"))
        self.gridLayout_3.addWidget(self.textBrowser_20, 1, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 0, 7, 1, 1)
        self.textBrowser_19 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_19.sizePolicy().hasHeightForWidth())
        self.textBrowser_19.setSizePolicy(sizePolicy)
        self.textBrowser_19.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_19.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_19.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_19.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_19.setObjectName(_fromUtf8("textBrowser_19"))
        self.gridLayout_3.addWidget(self.textBrowser_19, 1, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 1, 1, 1)
        self.textBrowser_24 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_24.sizePolicy().hasHeightForWidth())
        self.textBrowser_24.setSizePolicy(sizePolicy)
        self.textBrowser_24.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_24.setMaximumSize(QtCore.QSize(40, 24))
        self.textBrowser_24.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_24.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_24.setObjectName(_fromUtf8("textBrowser_24"))
        self.gridLayout_3.addWidget(self.textBrowser_24, 2, 0, 1, 1)
        self.textBrowser_17 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_17.sizePolicy().hasHeightForWidth())
        self.textBrowser_17.setSizePolicy(sizePolicy)
        self.textBrowser_17.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_17.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_17.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_17.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_17.setObjectName(_fromUtf8("textBrowser_17"))
        self.gridLayout_3.addWidget(self.textBrowser_17, 1, 6, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 4, 1, 1)
        self.textBrowser_18 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_18.sizePolicy().hasHeightForWidth())
        self.textBrowser_18.setSizePolicy(sizePolicy)
        self.textBrowser_18.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_18.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_18.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_18.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_18.setObjectName(_fromUtf8("textBrowser_18"))
        self.gridLayout_3.addWidget(self.textBrowser_18, 2, 6, 1, 1)
        self.textBrowser_15 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_15.sizePolicy().hasHeightForWidth())
        self.textBrowser_15.setSizePolicy(sizePolicy)
        self.textBrowser_15.setMinimumSize(QtCore.QSize(70, 20))
        self.textBrowser_15.setMaximumSize(QtCore.QSize(70, 24))
        self.textBrowser_15.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_15.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_15.setObjectName(_fromUtf8("textBrowser_15"))
        self.gridLayout_3.addWidget(self.textBrowser_15, 2, 7, 1, 1)
        self.textBrowser_22 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_22.sizePolicy().hasHeightForWidth())
        self.textBrowser_22.setSizePolicy(sizePolicy)
        self.textBrowser_22.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_22.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_22.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_22.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_22.setObjectName(_fromUtf8("textBrowser_22"))
        self.gridLayout_3.addWidget(self.textBrowser_22, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 6, 1, 1)
        self.textBrowser_16 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_16.sizePolicy().hasHeightForWidth())
        self.textBrowser_16.setSizePolicy(sizePolicy)
        self.textBrowser_16.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_16.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_16.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_16.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_16.setObjectName(_fromUtf8("textBrowser_16"))
        self.gridLayout_3.addWidget(self.textBrowser_16, 1, 7, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(58, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.textBrowser_21 = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.textBrowser_21.sizePolicy().hasHeightForWidth())
        self.textBrowser_21.setSizePolicy(sizePolicy)
        self.textBrowser_21.setMinimumSize(QtCore.QSize(0, 20))
        self.textBrowser_21.setMaximumSize(QtCore.QSize(20, 24))
        self.textBrowser_21.setBaseSize(QtCore.QSize(70, 20))
        self.textBrowser_21.setStyleSheet(_fromUtf8("background:rgb(243, 221, 255)"))
        self.textBrowser_21.setObjectName(_fromUtf8("textBrowser_21"))
        self.gridLayout_3.addWidget(self.textBrowser_21, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.saveButton = QtGui.QPushButton(Y86Simulator)
        self.saveButton.setGeometry(QtCore.QRect(450, 60, 75, 23))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.saveAdd = QtGui.QLineEdit(Y86Simulator)
        self.saveAdd.setGeometry(QtCore.QRect(530, 60, 371, 21))
        self.saveAdd.setObjectName(_fromUtf8("saveAdd"))

        self.retranslateUi(Y86Simulator)
        QtCore.QMetaObject.connectSlotsByName(Y86Simulator)

    def retranslateUi(self, Y86Simulator):
        Y86Simulator.setWindowTitle(_translate("Y86Simulator", "Y86 Simulator", None))
        self.label.setText(_translate("Y86Simulator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Harrington\'; font-size:14pt; font-weight:400; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600; font-style:normal; color:#ff557f;\">Y86 Simulator</span></p></body></html>", None))
        self.runButton.setText(_translate("Y86Simulator", "Run", None))
        self.stopButton.setText(_translate("Y86Simulator", "Stop", None))
        self.stepButton.setText(_translate("Y86Simulator", "Step", None))
        self.backButton.setText(_translate("Y86Simulator", "Back", None))
        self.resetButton.setText(_translate("Y86Simulator", "Reset", None))
        self.label_29.setText(_translate("Y86Simulator", "iCode", None))
        self.label_30.setText(_translate("Y86Simulator", "valC", None))
        self.label_31.setText(_translate("Y86Simulator", "valA", None))
        self.label_25.setText(_translate("Y86Simulator", "dstM", None))
        self.label_26.setText(_translate("Y86Simulator", "iFun", None))
        self.label_27.setText(_translate("Y86Simulator", "valB", None))
        self.label_28.setText(_translate("Y86Simulator", "dstE", None))
        self.label_32.setText(_translate("Y86Simulator", "srcA", None))
        self.label_33.setText(_translate("Y86Simulator", "srcB", None))
        self.label_39.setText(_translate("Y86Simulator", "rA", None))
        self.label_40.setText(_translate("Y86Simulator", "rB", None))
        self.label_34.setText(_translate("Y86Simulator", "iCode", None))
        self.label_36.setText(_translate("Y86Simulator", "valP", None))
        self.label_35.setText(_translate("Y86Simulator", "valC", None))
        self.label_38.setText(_translate("Y86Simulator", "iFun", None))
        self.label_43.setText(_translate("Y86Simulator", "predPC", None))
        self.loadButton.setText(_translate("Y86Simulator", "Load", None))
        self.label_7.setText(_translate("Y86Simulator", "interval", None))
        self.label_2.setText(_translate("Y86Simulator", "iCode", None))
        self.label_5.setText(_translate("Y86Simulator", "dstE", None))
        self.label_4.setText(_translate("Y86Simulator", "valM", None))
        self.label_3.setText(_translate("Y86Simulator", "valE", None))
        self.label_6.setText(_translate("Y86Simulator", "dstM", None))
        self.label_16.setText(_translate("Y86Simulator", "valE", None))
        self.label_15.setText(_translate("Y86Simulator", "dstM", None))
        self.label_17.setText(_translate("Y86Simulator", "Bch", None))
        self.label_12.setText(_translate("Y86Simulator", "valM", None))
        self.label_14.setText(_translate("Y86Simulator", "dstE", None))
        self.label_13.setText(_translate("Y86Simulator", "iCode", None))
        self.saveButton.setText(_translate("Y86Simulator", "Save", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Y86Simulator = QtGui.QDialog()
    ui = Ui_Y86Simulator()
    ui.setupUi(Y86Simulator)
    Y86Simulator.show()
    sys.exit(app.exec_())

